src/Entity/Supplier.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
/**
 * @ORM\Entity(repositoryClass="App\Repository\SupplierRepository")
 */
class Supplier
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    public $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=100)
     */
    public $name;

    /**
     * @ORM\Column(type="smallint")
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $contact_no;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $location;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;


    //---
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Product", mappedBy="supplier" )
     * ORM\@ORM\JoinColumn(name="id",referencedColumnName="supplier_id")
     */
    private $products;

    //--

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->products = new ArrayCollection();

    }

    public function getId()
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getContactNo(): ?string
    {
        return $this->contact_no;
    }

    public function setContactNo(?string $contact_no): self
    {
        $this->contact_no = $contact_no;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setSupplier($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getSupplier() === $this) {
                $product->setSupplier(null);
            }
        }

        return $this;
    }


    //-----

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SupplierStatus", inversedBy="", fetch="EAGER")
     * @ORM\JoinColumn(name="status", referencedColumnName="id")
     */
    private $supplierStatus;

    public function getSupplierStatus(): ?supplierStatus
    {
        return $this->supplierStatus;
    }

    public function setSupplier(?supplierStatus $supplierStatus): self
    {
        $this->supplier = $supplierStatus;

        return $this;
    }







}

src/Entity/SupplierStatus.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SupplierStatusRepository")
 */
class SupplierStatus
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    public $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    public $status_desc;


    public function __construct()
    {

    }
    public function getId()
    {
        return $this->id;
    }

    public function getStatusDesc(): ?string
    {
        return $this->status_desc;
    }

    public function setStatusDesc(string $status_desc): self
    {
        $this->status_desc = $status_desc;

        return $this;
    }





}

src/Form/SupplierType.php
<?php

namespace App\Form;

use App\Entity\Supplier;
use App\Entity\SupplierStatus;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Validator\Constraints as Assert;


class SupplierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // dd($options['choices']);
        foreach ($options['choices'] as $opt){
            $choices[$opt->status_desc] = $opt->id;
        }
//        dump($options['custom']);
        $builder
            ->add('code')
            ->add('name')
            // ->add('status', EntityType::class,[
            //     'class' => SupplierStatus::class,
            //     'choice_label' => 'status_desc',
            //     'placeholder' => '-select status'
            // ])
            ->add('status',ChoiceType::class, [
                'choices'=> $choices,
                'placeholder' => '-select supplier',
                'constraints' => array(
                    new Assert\Type(array(
                        'type' => 'integer',
                        'message' => 'number lang dito'
                    ))
                ),
            ])
            ->add('contact_no')
            ->add('location')
//            ->add('created_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Supplier::class,
            'choices' => null,
        ]);
    }
}

src/Controller/SupplierController.php
<?php

namespace App\Controller;

use App\Entity\Supplier;
use App\Form\SupplierType;
use App\Repository\SupplierRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use App\Entity\SupplierStatus;

/**
 * @Route("/supplier")
 */
class SupplierController extends Controller
{
    /**
     * @Route("/", name="supplier_index", methods="GET")
     */
    public function index(SupplierRepository $supplierRepository): Response
    {
        $suppliers = $supplierRepository->findAll();
        return $this->render('supplier/index.html.twig', ['suppliers' => $suppliers]);
    }

    /**
     * @Route("/new", name="supplier_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $supplier = new Supplier();
        $supplierStatus = $this->choiceSupplierStatus();
        $form = $this->createForm(SupplierType::class, $supplier, ['custom' => ['choices' => $supplierStatus]]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($supplier);
            $em->flush();

            return $this->redirectToRoute('supplier_index');
        }

        return $this->render('supplier/new.html.twig', [
            'supplier' => $supplier,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="supplier_show", methods="GET")
     */
    public function show(Supplier $supplier): Response
    {
        // dd($supplier);
        return $this->render('supplier/show.html.twig', ['supplier' => $supplier]);
    }

    /**
     * @Route("/{id}/edit", name="supplier_edit", methods="GET|POST")
     */
    public function edit(Request $request, Supplier $supplier): Response
    {
        $supplierStatus = $this->getDoctrine()->getRepository(SupplierStatus::class)->findAll();
        $choices = ['choices' => $supplierStatus];

        $form = $this->createForm(SupplierType::class, $supplier,$choices);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('notice' ,'Supplier successfully updated');
            return $this->redirectToRoute('supplier_edit', ['id' => $supplier->getId()]);
        }

        return $this->render('supplier/edit.html.twig', [
            'supplier' => $supplier,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="supplier_delete", methods="DELETE")
     */
    public function delete(Request $request, Supplier $supplier): Response
    {
        if ($this->isCsrfTokenValid('delete'.$supplier->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($supplier);
            $em->flush();
        }

        return $this->redirectToRoute('supplier_index');
    }

    public function choiceSupplierStatus(){
        $data['-select one-'] = '';
        $em = $this->getDoctrine()->getManager();
        $suppliers = $em->getRepository(SupplierStatus::class)->findAll();

        foreach($suppliers as $supp){
            $data[$supp->status_desc] = $supp->id;
        }

        return $data;
    }
}

templates/supplier/_delete_form.html.twig
{{ include('product/_delete_post_confirmation.html.twig') }}
<form method="post" action="{{ path('supplier_delete', {'id': supplier.id}) }}" 
{# onsubmit="return confirm('Are you sure you want to delete this item?');" #}
 data-confirmation=true >
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ supplier.id) }}">
    <button class="btn">Delete</button>
</form>

templates/supplier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Supplier{% endblock %}

{% block body %}
    <h1>Edit Supplier</h1>

    {{ include('supplier/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('supplier_index') }}">back to list</a>

    {{ include('supplier/_delete_form.html.twig') }}
{% endblock %}

templates/supplier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Supplier index{% endblock %}

{% block body %}
    <h1>Supplier index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Code</th>
                <th>Name</th>
                <th>Status</th>
                <th>Contact_no</th>
                <th>Location</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for supplier in suppliers %}
            <tr>
                <td>{{ supplier.id }}</td>
                <td>{{ supplier.code }}</td>
                <td>{{ supplier.name }}</td>
                <td>
                    {# {{ supplier.status }} #}
                    {{ supplier.supplierStatus().statusDesc is defined ? supplier.supplierStatus().statusDesc : ''}}
                </td>
                <td>{{ supplier.contactNo }}</td>
                <td>{{ supplier.location }}</td>
                <td>{{ supplier.createdAt ? supplier.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('supplier_show', {'id': supplier.id}) }}">show</a>
                    <a href="{{ path('supplier_edit', {'id': supplier.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('supplier_new') }}">Create new</a>
{% endblock %}

templates/supplier/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Supplier{% endblock %}

{% block body %}
    <h1>Create new Supplier</h1>

    {{ include('supplier/_form.html.twig') }}

    <a href="{{ path('supplier_index') }}">back to list</a>
{% endblock %}

templates/supplier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Supplier{% endblock %}

{% block body %}
    <h1>Supplier</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ supplier.id }}</td>
            </tr>
            <tr>
                <th>Code</th>
                <td>{{ supplier.code }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ supplier.name }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ supplier.status }}
                    {{ supplier.supplierStatus().statusDesc is defined ? supplier.supplierStatus().statusDesc : ''}}
                </td>
            </tr>
            <tr>
                <th>Contact_no</th>
                <td>{{ supplier.contactNo }}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td>{{ supplier.location }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ supplier.createdAt ? supplier.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('supplier_index') }}">back to list</a>

    <a href="{{ path('supplier_edit', {'id': supplier.id}) }}">edit</a>

    {{ include('supplier/_delete_form.html.twig') }}
{% endblock %}