src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $product_code;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="integer", nullable=true)
     *
     */
    private $supplier_id;

    /**
     * @ORM\Column(type="float")
     */
    private $supplier_price;

    /**
     * @ORM\Column(type="float")
     */
    private $interest_rate;

    /**
     * @ORM\Column(type="float")
     */
    private $computed_price;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $online_price;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $product_status;



    public function __construct()
    {
        $this->created_at = new \DateTime();
    }
    
    public function getId()
    {
        return $this->id;
    }

    public function getProductCode(): ?string
    {
        return $this->product_code;
    }

    public function setProductCode(string $product_code): self
    {
        $this->product_code = $product_code;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSupplierId(): ?int
    {
        return $this->supplier_id;
    }

    public function setSupplierId( $supplier_id): self
    {
        $this->supplier_id = $supplier_id;
//        $this->supplier_id = $supplier_id instanceof Product ? $supplier_id->getId() : $supplier_id;

        return $this;
    }

    public function getSupplierPrice(): ?float
    {
        return $this->supplier_price;
    }

    public function setSupplierPrice(?float $supplier_price): self
    {
        $this->supplier_price = $supplier_price;

        return $this;
    }

    public function getInterestRate(): ?float
    {
        return $this->interest_rate;
    }

    public function setInterestRate(float $interest_rate): self
    {
        $this->interest_rate = $interest_rate;

        return $this;
    }

    public function getComputedPrice(): ?float
    {
        return $this->computed_price;
    }

    public function setComputedPrice(float $computed_price): self
    {
        $this->computed_price = $computed_price;

        return $this;
    }

    public function getOnlinePrice(): ?float
    {
        return $this->online_price;
    }

    public function setOnlinePrice(?float $online_price): self
    {
        $this->online_price = $online_price;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getProductStatus(): ?int
    {
        return $this->product_status;
    }

    public function setProductStatus(?int $product_status): self
    {
        $this->product_status = $product_status;

        return $this;
    }


//-----

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Supplier", inversedBy="products", fetch="EAGER")
     * @ORM\JoinColumn(name="supplier_id", referencedColumnName="id")
     */
    private $supplier;

    public function getSupplier(): ?Supplier
    {
        return $this->supplier;
    }

    public function setSupplier(?Supplier $supplier): self
    {
        $this->supplier = $supplier;

        return $this;
    }






}

src/Form/ProductType.php
<?php

namespace App\Form;
use App\Entity\Product;
use App\Entity\Supplier;

use PhpParser\Node\Expr\Cast\Int_;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;

use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Validator\Constraints as Assert;



class ProductType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        foreach ($options['choices'] as $opt){
            $choices[$opt->name] = $opt->id;
        }
//dd($builder);
        $builder
            ->add('product_code')
            ->add('description')
//            ->add('supplier_id', EntityType::class, [
//                'class' => Supplier::class,
//                'choice_label' => 'name',
//                'choice_value' => 'id',
//                'placeholder' => '-select supplier-',
//                'constraints' => array(
//                    new Assert\Type(array(
//                        'type' => 'integer',
//                        'message' => 'number lang dito'
//                    ))
//                )
//            ])
            ->add('supplier_id',ChoiceType::class, [
                'choices'=> $choices,
                'placeholder' => '-select supplier',
                'constraints' => array(
                    new Assert\Type(array(
                        'type' => 'integer',
                        'message' => 'number lang dito'
                    ))
                ),
            ])
            ->add('supplier_price')
            ->add('interest_rate')
            ->add('computed_price',TextType::class, [
                    'attr' => ['readonly' => 'readonly']
            ])
            ->add('online_price')
            ->add('img', FileType::class, [
                'data_class' => null,
                'label' => 'Select image',
                'required' => false,
                'attr' => [
                    'class' => 'form-control',
                    'accept' => 'image/jpg,image/jpeg, image/png',
                ]
            ]);

    }





    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
            'choices' => null,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Entity\SupplierStatus;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use App\Service\FileUploader;
use App\Entity\Supplier;
use Symfony\Component\HttpFoundation\File\File;



/**
 * @Route("/product")
 */
class ProductController extends Controller
{
    /**
     * @Route("/", name="product_index", methods="GET")
     */
    public function index( Request $request): Response
    {
//        dd($request->query->all())
        $query    = $this->getDoctrine()->getRepository(Product::class)->testfind($request);
        $per_page = $request->query->getInt('per_page',10);

        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            $per_page/*limit per page*/
        );

        return $this->render('product/index.html.twig', [
                'products' => $pagination,
                'page' => $pagination->getCurrentPageNumber(),
                'searchBy' => $request->query->get('searchBy', []),
                'qsearch' => trim($request->query->get('qsearch','')),
                'sort'=> $request->query->get('sort','p.created_at'),
                'direction' => $request->query->get('direction','DESC'),
                'per_page' => $per_page,
                'layout' => $request->query->get('layout',1),
        ]);
    }

    /**
     * @Route("/new", name="product_new", methods="GET|POST")
     */
    public function new(Request $request, FileUploader $file): Response
    {
        $product = new Product();

        $supplier = $this->getDoctrine()->getRepository(Supplier::class)->findAll();
        $choices = ['choices' => $supplier];

        $form = $this->createForm(ProductType::class, $product ,$choices);


        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file->uploadDirectory('uploads/file');
            if($form['img']->getData()){
                $file_name = $file->upload($form['img']->getData());
                $product->setImg($file_name);
            }

            $em = $this->getDoctrine()->getManager();
            $computed_price = ( 1 + ($form['interest_rate']->getData() / 100)) * $form['supplier_price']->getData();
            $product->setComputedPrice($computed_price);

            $supplier = $this->getDoctrine()->getRepository(Supplier::class)->find($form['supplier_id']->getData());
            $product->setSupplier($supplier);
            $em->persist( $product) ;
            $em->flush();
            $this->addFlash('notice','Product successfully added');
            return  $this->redirectToRoute('product_edit',['id'=> $product->getId()]);
        }

        return $this->render('product/new.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }




    /**
     * @Route("/{id}", name="product_show", methods="GET")
     */
    public function show(Product $product): Response
    {
//        dd($product);
        return $this->render('product/show.html.twig', ['product' => $product]);
    }

    /**
     * @Route("/{id}/edit", name="product_edit", methods="GET|POST")
     */
    public function edit(Request $request, Product $product, FileUploader $fileupload ) : Response
    {


     $old_image = $product->getImg();
        $supplier = $this->getDoctrine()->getRepository(Supplier::class)->findAll();
        $choices = ['choices' => $supplier];
//        dump($this->getParameter('upload_path').$product->getImg());
//        $img = $this->getParameter('upload_path').$product->getImg();
//        if($product->getImg()){
//            $product->setImg(
//                new File($img)
//            );
//        }



        $form = $this->createForm(ProductType::class, $product, $choices );
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){


            if($form['img']->getData()){
                $this->delete_img($old_image);
                $file_name = $fileupload->upload($form['img']->getData());
                $product->setImg($file_name);
            }else{
                $product->setImg($old_image);
            }
            $computed_price = ( 1 + ($form['interest_rate']->getData() / 100)) * $form['supplier_price']->getData();
            $product->setComputedPrice($computed_price);
//            dd($computed_price);
            $em =   $this->getDoctrine()->getManager();
            $em->flush();
            $this->addFlash('notice' ,'Product successfully updated');
            return $this->redirectToRoute('product_edit', ['id' => $product->getId()]);
        }

        return $this->render('product/edit.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="product_delete", methods="DELETE")
     */
    public function delete(Request $request, Product $product): Response
    {
        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($product);
            $em->flush();
        }
        $this->addFlash('notice','Product successfully deleted.');
        return $this->redirectToRoute('product_index');
    }

//    public function suppliers(){
//        $data['-select one-'] = '';
//        $em = $this->getDoctrine()->getManager();
//        $suppliers = $em->getRepository(Supplier::class)->findAll();
//
//
//        foreach($suppliers as $supp){
//            $data[$supp->name] = $supp->id;
//        }
//
//        return $data;
//
//
//    }

    private function delete_img($image_name){

        if($image_name  != '' && file_exists($this->getParameter('upload_path').$image_name))
        {
            unlink($this->getParameter('upload_path').$image_name);
        }
    }


}

templates/product/_delete_form.html.twig
{{ include('product/_delete_post_confirmation.html.twig') }}
<form method="post" action="{{ path('product_delete', {'id': product.id}) }}" 
{# onsubmit="return confirm('Are you sure you want to delete this item?');"  #}
data-confirmation=true>
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn btn-danger pull-left">Delete</button>
</form>

templates/product/_delete_post_confirmation.html.twig
{# Bootstrap modal, see http://getbootstrap.com/javascript/#modals #}
<div class="modal fade" id="confirmationModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <h4>
                    {# {{ 'delete_post_modal.title'|trans }} #}
                    Are you sure you want to delete?
                </h4>
                <p>This action cannot be undone.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="btnNo" data-dismiss="modal">
                    <i class="fa fa-ban" aria-hidden="true"></i> Cancel
                </button>
                <button type="button" class="btn btn-danger" id="btnYes" data-dismiss="modal">
                    <i class="fa fa-trash" aria-hidden="true"></i> Yes
                </button>
            </div>
        </div>
    </div>
</div>

templates/product/_form.html.twig
{#<div class="row">#}
{#<div class="col-xs-offset-1 col-xs-10">#}
    {{ form_start(form) }}

    {{ form_widget(form) }}
    <button class="btn btn-info pull-right">{{ button_label|default('Save') }}</button>

    {{ form_end(form) }}
{#</div>#}
{#</div>#}

templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Product{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-xs-12"><a href="{{ path('product_index') }}">back to list</a></div>
        <div class="col-md-8">
            <h1 class="col-xs-offset-1 col-xs-10">Edit Product</h1>
            {{ include('product/_form.html.twig', {'button_label': 'Update'}) }}
            {{ include('product/_delete_form.html.twig') }}
        </div>
        <div class="col-md-4">
            <h1>Image</h1>

            {% if product.img != '' %}
                <a href="{{ asset('uploads/'~product.img) }}">
                    <img class="img-thumbnail image img-responsive thumbnail img-thumbnail" src="{{ asset('uploads/'~product.img) }}" style="max-width: 300px" />
                </a>
            {%  else %}
                <div class="fixed-bottom">
                    <img class="img-thumbnail image img-responsive thumbnail img-thumbnail" src="{{ asset('_images/no_image.jpg') }}" style="max-width: 300px" />
                </div>



            {% endif %}
            <div class="clearfix"> </div>
        </div>
    </div>








{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Product List{% endblock %}
{% block header %}
<style>
    .fa-check{
        color:green;
    }
    .tooltip{
        z-index: 90000;
    }
</style>
    <h1>Product List &nbsp;

        <span class="dropdown">

                <a class=" dropdown-toggle pointer" type="button" data-toggle="dropdown" >
                     <tip data-toggle="tooltip" data-placement="left" title="filter">
                        <i class="fa fa-search"></i>
                     </tip>
                </a>

            <ul class="dropdown-menu shadow " style="width: 300px; padding: 10px">
                <form action="{{ path('product_index',{ per_page: per_page, direction: direction, sort:sort }) }}" method="GET">
                    {#<li class="dropdown-header">Search by:</li>#}

                    <li><a href="#" onclick="javascript:void(0)">
                            {#<input name="page" type="hidden" value="{{ page }}">#}
                            <input value="{{ per_page }}" name="per_page" type="hidden">
                            <input value="{{ direction }}" name="direction" type="hidden">
                            <input value="{{ sort }}" name="sort" type="hidden">
                             <label>
                                 <input type="checkbox" name="searchBy[]" value="p.product_code" {{ ('p.product_code' in searchBy)  or  (qsearch == '') ? 'checked' : '' }}>
                                 Product code</label>
                         </a>
                     </li>
                    <li><a href="#" onclick="javascript:void(0)">
                            <label><input type="checkbox" name="searchBy[]" value="p.description" {{ 'p.description' in searchBy or  (qsearch == '') ? 'checked' : '' }}> Description</label>
                        </a>
                    </li>
                    <li><a href="#" onclick="javascript:void(0)">
                            <label><input type="checkbox" name="searchBy[]" value="s.name" {{ 's.name' in searchBy or  (qsearch == '') ? 'checked' : '' }}> Supplier</label>
                        </a>
                    </li>
                    <li>
                        <a>
                            <div class="input-group">
                                <input type="text" class="form-control" name="qsearch" value="{{ qsearch }}" placeholder="Search for...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit"><i class="fa fa-search"></i> </button>
                                </span>
                            </div><!-- /input-group -->
                        </a>
                    </li>
                </form>
            </ul>

        </span>
        &nbsp;

        <span  class="dropdown">
            <a class=" dropdown-toggle pointer"  data-toggle="dropdown" >
                <tip data-toggle="tooltip" data-placement="right" title="sorting">
                    <i class="fa fa-sort-alpha-asc"></i></a>
                </tip>
            <ul class="dropdown-menu shadow">
                <li class="dropdown-header text-bold">Date</li>
                <li class=""><a href="{{ path('product_index',{ per_page: per_page, page:page, searchBy:searchBy , qsearch:qsearch, sort: 'p.created_at' , direction: 'asc'}) }}">ascending
                        <i class=" {{ sort~direction == 'p.created_atasc' ? 'fa fa-check'}}" ></i>
                    </a>
                </li>
                <li class=""><a href="{{ path('product_index',{ per_page: per_page,page:page, searchBy:searchBy , qsearch:qsearch, sort: 'p.created_at' , direction: 'desc'}) }}">descending
                        <i class=" {{ sort~direction == 'p.created_atdesc' ? 'fa fa-check'}}" ></i>
                    </a>
                </li>
                <li class="divider"></li>

                <li class="dropdown-header text-bold">Code</li>
                <li class=""><a href="{{ path('product_index',{ per_page: per_page,page:page, searchBy:searchBy , qsearch:qsearch, sort: 'p.product_code' , direction: 'asc'}) }}">ascending
                        <i class=" {{ sort~direction == 'p.product_codeasc' ? 'fa fa-check'}}" ></i>
                    </a>
                </li>
                <li class=""><a href="{{ path('product_index',{per_page: per_page, page:page, searchBy:searchBy , qsearch:qsearch, sort: 'p.product_code' , direction: 'desc'}) }}">descending
                        <i class=" {{ sort~direction == 'p.product_codedesc' ? 'fa fa-check'}}" ></i>
                    </a>
                </li>
                <li class="divider"></li>

                <li class="dropdown-header text-bold">Resell Price</li>
                <li class=""><a href="{{ path('product_index',{per_page: per_page, page:page, searchBy:searchBy , qsearch:qsearch, sort: 'p.computed_price' , direction: 'asc'}) }}">ascending
                        <i class=" {{ sort~direction == 'p.computed_priceasc' ? 'fa fa-check'}}" ></i>
                    </a>
                </li>
                <li class=""><a href="{{ path('product_index',{per_page: per_page, page:page, searchBy:searchBy , qsearch:qsearch, sort: 'p.computed_price' , direction: 'desc'}) }}">descending
                        <i class=" {{ sort~direction == 'p.computed_pricedesc' ? 'fa fa-check'}}" ></i>
                    </a>
                </li>


            </ul>
        </span>
         &nbsp;
        <span class="dropdown">
            <a class=" dropdown-toggle pointer"  data-toggle="dropdown" >
                <tip data-toggle="tooltip" data-placement="right" title="page limit, layout">
                    <i class="fa fa-cogs"></i>
                </tip>
            </a>
            <ul class="dropdown-menu shadow">
                <li class="dropdown-header">Records per page</li>
                <li><a href="{{ path('product_index', { searchBy: searchBy, qsearch:qsearch, sort: sort,direction:direction, per_page: 10}) }}">
                        10 &nbsp; <i class="{{ per_page == 10 ? ' fa fa-check' }}"></i></a>
                </li>
                <li><a href="{{ path('product_index', { searchBy: searchBy, qsearch:qsearch, sort: sort,direction:direction, per_page: 20}) }}">
                        20 &nbsp; <i class="{{ per_page == 20 ? 'fa fa-check' }} "></i></a></a>
                </li>
                <li><a href="{{ path('product_index', { searchBy: searchBy, qsearch:qsearch, sort: sort,direction:direction, per_page: 30}) }}">
                        30 &nbsp; <i class="{{ per_page == 30 ? 'fa fa-check' }} "></i></a></a>
                </li>
                <li class="divider"></li>
                <li class="dropdown-header">Layout</li>
                <li>
                    <a href="{{ path('product_index', { page:page, per_page:per_page, searchBy:searchBy, qsearch:qsearch, sort:sort,direction:direction, layout:1 }) }}">
                        <i class="fa fa-th-large"></i>
                         <i class="{{ layout == 1 ? 'fa fa-check' }} "></i>
                    </a>

                </li>
                <li>
                    <a href="{{ path('product_index', { page:page, per_page:per_page, searchBy:searchBy, qsearch:qsearch, sort:sort,direction:direction, layout:2 }) }}">
                        <i class="fa fa-align-justify"></i>
                        <i class="{{ layout == 2 ? 'fa fa-check' }} "></i>
                    </a>

                </li>
            </ul>
        </span>




    </h1>
    <a href="{{ path('product_new') }}" class="btn btn-success  pull-right " style="margin-top:-30px"><i class="fa fa-plus-circle"></i>Create new</a>

{% endblock %}
{% block body %}

<div class="row">
<div class="col-xs-12">
    {% for product in products %}
        <div class="{{ (layout == 1 )  ? 'col-md-6' : 'col-xs-12 prod-container'  }}  " >
            {%  if(layout == 1)  %}
            <div class="col-xs-12 prod-container ">
            {% endif %}
            <div class="col-sm-2 col-xs-3 prod-image text-center" style="padding: 0">
                {% if product.img != '' %}
                    <a class="fancybox" rel="gallery1" href="{{ asset('uploads/'~product.img) }}" title="{{ product.description }}">
                        <img class="img-fluid img-responsive " src="{{ asset('uploads/'~product.img) }}" alt="image deleted"  />
                    </a>

                {% else %}
                    <img class="img-fluid img-responsive " src="{{ asset('_images/no_image.jpg') }}"  />
                {% endif %}
            </div>
            <div class="col-sm-10 col-xs-9 " style="padding: 7px">
                <div class="div-table">
                    <div class="div-row">
                        <div >Code</div>
                        <div>
                            {{ product.productCode }}
                        </div>
                    </div>
                    <div class="div-row">
                        <div >Description
                        </div>
                        <div>
                            {{ product.description }}
                        </div>
                    </div>
                    <div class="div-row">
                        <div >Supplier</div>
                        <div>
                            {{  product.supplier().name is defined ? product.supplier().name : ''  }}
                        </div>
                    </div>
                    <div class="div-row">
                        <div >Supplier Price</div>
                        <div>
                            {{ product.supplierPrice }}
                        </div>
                    </div>
                    <div class="div-row">
                        <div >Interest</div>
                        <div>
                            {{  product.interestRate }}
                        </div>
                    </div>
                    <div class="div-row">
                        <div >Resell Value</div>
                        <div>
                            {{  product.computedPrice  }}
                        </div>
                    </div>
                    <div class="div-row">
                        <div >Online Price</div>
                        <div>
                            {{  product.onlinePrice }}
                        </div>
                    </div>
                    <div class="div-row">
                        <div >Date Added</div>
                        <div>
                            {{ product.createdAt|date('M d,\'y h:i A') }}
                        </div>
                    </div>
                    <div class="div-row">
                        <div ></div>
                        <div>
                            <a href="{{ path('product_show', {'id': product.id}) }}" class="btn btn-warning pull-right"  style="margin-left: 5px"  >show</a>
                             <a href="{{ path('product_edit', {'id': product.id}) }}" class="btn btn-primary pull-right">edit</a>
                        </div>
                    </div>

                </div   >
            </div>
            {% if(layout == 1) %}
            </div> {#end 2 row div#}
            {% endif %}
        </div>
    {% else %}
        <div class="text-warning small">No records found
            {{ ( qsearch != '') ? 'for "'~qsearch~'".' : '.' }}
        </div>
    {% endfor %}
</div>
<div class="col-xs-12">
    {{ knp_pagination_render(products) }}
</div>
</div>



{% endblock %}

{% block css %}

{% endblock %}
{% block scripts %}
    {#<script type="text/javascript" src="http://fancyapps.com/fancybox/source/jquery.fancybox.pack.js?v=2.1.7"></script>#}
    {#<link rel="stylesheet" href="http://fancyapps.com/fancybox/source/jquery.fancybox.css?v=2.1.7">#}
    <script src="{{ asset('fancybox/fancybox.js') }}"></script>
    <link rel="stylesheet" href="{{ asset('fancybox/fancybox.css') }}">
    <script type="text/javascript">
        $(function(){

            $(".fancybox").fancybox();
            $('[data-toggle="tooltip"], .tooltip').tooltip();
            $('.dropdown-toggle').dropdown();
        });

    </script>

{% endblock %}

templates/product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Product{% endblock %}

{% block body %}
    <h1>Create new Product</h1>

    {{ include('product/_form.html.twig') }}

    <a href="{{ path('product_index') }}">back to list</a>
{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product{% endblock %}

{% block body %}
    <style>
        .div-row div:nth-child(1){
            min-width: 200px;

        }

        .div-row div:nth-child(2){
            padding-left: 10px;

        }

        .div-table{
            font-size: 2rem;
        }
    </style>
    <div class="row">
        <div class="col-md-6 "><a href="{{ path('product_index') }}">back to list</a></div>
    </div>
    <h1>Product</h1>
    <div class="col-md-12">
    <div class="div-table div-table-striped div-table-bordered">

            <div class="div-row">
                <div>Id</div>
                <div>{{ product.id }}</div>
            </div>
            <div class="div-row">
                <div>Product Code</div>
                <div>{{ product.productCode }}</div>
            </div>
            <div class="div-row">
                <div>Description</div>
                <div>{{ product.description }}</div>
            </div>
            <div class="div-row">
                <div>Supplier</div>
                <div>{{ product.supplier.name is defined ? product.supplier.name : '' }}</div>
            </div>
            <div class="div-row">
                <div>Supplier Price</div>
                <div> {{  product.supplierPrice  }}</div>
            </div>
            <div class="div-row">
                <div>Interest rate</div>
                <div>{{ product.interestRate }}</div>
            </div>
            <div class="div-row">
                <div>Computed   price</div>
                <div>{{ product.computedPrice }}</div>
            </div>
            <div class="div-row">
                <div>Online Price</div>
                <div>{{ product.onlinePrice }}</div>
            </div>
            {% if(product.img != "") %}
            <div class="div-row">
                <div>Image</div>
                <div><img class="img-thumbnail image img-responsive img-circle" src="{{ asset('uploads/') }}{{ product.img }}" />   </div>
            </div>
            {% endif %}

    </div>
    </div>
    <div class="row">

        <div class="col-md-12 text-right"><a href="{{ path('product_edit', {'id': product.id}) }}" class="btn btn-primary">edit</a></div>



    </div>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}